# Generated by Django 4.2.3 on 2023-08-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcategory',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatcategory',
            name='pdf_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
