# Generated by Django 4.2.3 on 2023-08-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_chatcategory_time_alter_chatcategory_pdf_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='pdf_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
