# Generated by Django 4.2.3 on 2023-08-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_chatmessage_remove_chat_name_remove_chat_output_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='prompt',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='replay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
