# Generated by Django 4.2.3 on 2023-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='API Cost Per 1k Words', max_length=500)),
                ('cost_amount', models.IntegerField(default=0.5)),
            ],
        ),
        migrations.RemoveField(
            model_name='stripkey',
            name='key',
        ),
        migrations.AddField(
            model_name='stripkey',
            name='public_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stripkey',
            name='secrect_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='openaikey',
            name='key',
            field=models.CharField(max_length=500),
        ),
    ]
