# Generated by Django 4.2.3 on 2023-08-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_apicost_remove_stripkey_key_stripkey_public_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicost',
            name='cost_amount',
            field=models.FloatField(default=0.5),
        ),
    ]
